### ISSUE TITLE
Requests and observables are not unsubscribed when the view is gone

### ISSUE THREAD

**Issue by sebaslogen** [krokers/exchange-rates-mvvm#1]
Network requests and observables are loaded with onLoad() method when the CurrenciesActivity view is created but when the views are paused or destroyed, the requests and subscriptions are not canceled/un-subscribed because method `CurrencyListViewModel.dispose()` is not being called.

**Comment by krokers** [comment]
Good catch. Thanks for review :)
Fix applied.

**Comment by sebaslogen** [comment]
No problem.
I'm super curious because another side effect of this with MVP would be that you'll try change a view that is not visible and Android will throw a fatal exception. Your example is using DataBinding, so I'm curious if you notifyPropertyChanged while the view is gone and if the DataBinding is already protected to avoid calling the view in this case.

**Comment by krokers** [comment]
In this case, it would cause small short time memory leak. View Model would stay in memory little longer than it needs to be - until the background operation is finished.
It's not a problem for Activity. It will be garbage collected anyway, because ViewModel does not hold any reference to the View. That is another advantage of MVVM over MVP.

No crash is expected because ViewModel knows nothing about observers.  And when observer is gone, it won't be notified of the change.
